spring.application.name=gateway
server.port=8080
spring.threads.virtual.enabled=true
# Rota 0
spring.cloud.gateway.routes[0].id=AUTH-SERVICE
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Rota 1
spring.cloud.gateway.routes[1].id=DASHBOARD-SERVICE
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/dashboard/**

# Rota 2
spring.cloud.gateway.routes[2].id=CONSULTAS-SERVICE
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/consultas/**

# Rota 3
spring.cloud.gateway.routes[3].id=EQUIPE-SERVICE
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/equipe/**

# Rota 4
spring.cloud.gateway.routes[4].id=PACIENTES-SERVICE
spring.cloud.gateway.routes[4].uri=http://localhost:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/pacientes/**

# Rota 5
spring.cloud.gateway.routes[5].id=PROFISSIONAIS-SERVICE
spring.cloud.gateway.routes[5].uri=http://localhost:8086
spring.cloud.gateway.routes[5].predicates[0]=Path=/profissionais/**

# Rota 6
spring.cloud.gateway.routes[6].id=RELATORIO-SERVICE
spring.cloud.gateway.routes[6].uri=http://localhost:8087
spring.cloud.gateway.routes[6].predicates[0]=Path=/relatorio/**

# Rota 7
spring.cloud.gateway.routes[7].id=RABBIT
spring.cloud.gateway.routes[7].uri=http://localhost:8088
spring.cloud.gateway.routes[7].predicates[0]=Path=/rabbit/**